[global]
charset = utf-8
max connections = 8
reverse lookup = no

[codex]
path = /codex
uid = root
gid = root
read only = no
auth users = codex
secrets file = /etc/rsyncd.secrets
strict modes = false
