# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  # Proxmox Settings
  proxmoxLXC = {
    manageNetwork = false;
    privileged = false;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
