#:schema https://www.schemastore.org/traefik-v3-file-provider.json

[http.middlewares.cors.headers.customResponseHeaders]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "*"
Access-Control-Allow-Headers = "*"

[http.middlewares.security-headers.headers]
browserXssFilter = true
contentTypeNosniff = true
frameDeny = true
stsIncludeSubdomains = true
stsPreload = true
stsSeconds = 31536000

[http.middlewares.rate-limit.rateLimit]
average = 100
period = "1s"
burst = 200

[http.middlewares.crowdsec.plugin.bouncer]
enabled = true
defaultDecisionSeconds = 15
crowdsecMode = "live"
crowdsecLapiKeyFile = "/secrets/crowdsec/lapi_key"
# crowdsecLapiHost is supplied by default.nix.
crowdsecLapiScheme = "http"
crowdsecLapiTLSInsecureVerify = false
captchaProvider = "turnstile"
captchaSiteKeyFile = "/secrets/turnstile/site_key"
captchaSecretKeyFile = "/secrets/turnstile/secret_key"
captchaGracePeriodSeconds = 1800
captchaHTMLFilePath = "/captcha.html"
forwardedHeadersTrustedIPs = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
clientTrustedIPs = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[http.middlewares.auth-trev.basicAuth]
removeHeader = true
usersFile = "/secrets/user-trev"

[http.middlewares.auth-admin.basicAuth]
removeHeader = true
usersFile = "/secrets/user-admin"

[http.middlewares.secure.chain]
middlewares = ["security-headers", "rate-limit"]

[http.middlewares.secure-trev.chain]
middlewares = ["rate-limit", "auth-trev"]

[http.middlewares.secure-admin.chain]
middlewares = ["rate-limit", "auth-admin"]
