name: check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@6fc824c802d17c270315eb3c671500398d5ca7c0 # v1.60.1

      - name: Run checks
        run: nix flake check

  notify:
    if: ${{ github.event_name == 'push' }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Publish update
        env:
          REVISION: ${{ github.sha }}
        run: curl --fail-with-body --retry 3 --data-binary "$REVISION" https://ntfy.sh/spotdemo4-nix-main

  build:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@6fc824c802d17c270315eb3c671500398d5ca7c0 # v1.60.1

      - name: Build packages
        uses: ./.github/actions/build
