name: check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.hosts.outputs.hosts }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@468df9f0e52570a28a9368f4eaee60a8d3847f66 # v1.39.0
        with:
          shell: check

      - name: Run checks
        run: nix flake check

      - id: hosts
        name: Get hosts
        run: bash .github/hosts.sh

  build:
    needs: check
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJSON(needs.check.outputs.hosts) }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@468df9f0e52570a28a9368f4eaee60a8d3847f66 # v1.39.0
        with:
          shell: check

      - name: Build packages
        run: |
          nix-fast-build \
            --skip-cached \
            --no-nom \
            --flake ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"

  build-status:
    needs: [check, build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Failed
        if: ${{ (contains(needs.*.result, 'failure')) || (contains(needs.*.result, 'cancelled')) }}
        run: exit 1

      - name: Success
        run: echo "All jobs completed successfully."
