name: flake

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: spotdemo4/nix/.github/actions/init@main
        with:
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: flake-checker -f
