name: flake

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: spotdemo4/nix/.github/actions/init@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: flake-checker -f
