name: flake

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/actions/init
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: flake-checker -f
